export const storyGenres = [
    { value: "Action", label: "Action" },
    { value: "Adventure", label: "Adventure" },
    { value: "Alternate History", label: "Alternate History" },
    { value: "Anthology", label: "Anthology" },
    { value: "Apocalyptic", label: "Apocalyptic" },
    { value: "Bildungsroman", label: "Bildungsroman" },
    { value: "Biographical", label: "Biographical" },
    { value: "Chick Lit", label: "Chick Lit" },
    { value: "Children's", label: "Children's" },
    { value: "Coming-of-Age", label: "Coming-of-Age" },
    { value: "Comedy", label: "Comedy" },
    { value: "Crime", label: "Crime" },
    { value: "Cyberpunk", label: "Cyberpunk" },
    { value: "Drama", label: "Drama" },
    { value: "Dystopian", label: "Dystopian" },
    { value: "Erotic", label: "Erotic" },
    { value: "Experimental", label: "Experimental" },
    { value: "Fantasy", label: "Fantasy" },
    { value: "Feminist", label: "Feminist" },
    { value: "Folktale", label: "Folktale" },
    { value: "Ghost Story", label: "Ghost Story" },
    { value: "Gothic", label: "Gothic" },
    { value: "Historical", label: "Historical" },
    { value: "Horror", label: "Horror" },
    { value: "Humor", label: "Humor" },
    { value: "Juvenile", label: "Juvenile" },
    { value: "Legal Thriller", label: "Legal Thriller" },
    { value: "Literary Fiction", label: "Literary Fiction" },
    { value: "Magical Realism", label: "Magical Realism" },
    { value: "Mystery", label: "Mystery" },
    { value: "Mythology", label: "Mythology" },
    { value: "Nautical", label: "Nautical" },
    { value: "New Adult", label: "New Adult" },
    { value: "Non-Fiction", label: "Non-Fiction" },
    { value: "Philosophical", label: "Philosophical" },
    { value: "Picture Book", label: "Picture Book" },
    { value: "Poetry", label: "Poetry" },
    { value: "Political Thriller", label: "Political Thriller" },
    { value: "Psychological Thriller", label: "Psychological Thriller" },
    { value: "Realistic Fiction", label: "Realistic Fiction" },
    { value: "Romance", label: "Romance" },
    { value: "Satire", label: "Satire" },
    { value: "Science Fiction", label: "Science Fiction" },
    { value: "Self-Help", label: "Self-Help" },
    { value: "Short Story", label: "Short Story" },
    { value: "Slipstream", label: "Slipstream" },
    { value: "Social Commentary", label: "Social Commentary" },
    { value: "Speculative Fiction", label: "Speculative Fiction" },
    { value: "Steampunk", label: "Steampunk" },
    { value: "Superhero", label: "Superhero" },
    { value: "Suspense", label: "Suspense" },
    { value: "Thriller", label: "Thriller" },
    { value: "Time Travel", label: "Time Travel" },
    { value: "Tragedy", label: "Tragedy" },
    { value: "Urban Fantasy", label: "Urban Fantasy" },
    { value: "Utopian", label: "Utopian" },
    { value: "Vampire Fiction", label: "Vampire Fiction" },
    { value: "War", label: "War" },
    { value: "Western", label: "Western" },
    { value: "Young Adult", label: "Young Adult" }
]