// SETTING DETAILS
const settingDetails = {
    timeOfDay: ["morning", "afternoon", "evening", "night"],
    weather: ["sunny", "rainy", "snowy", "foggy", "windy"],
    location: [
        "City",
        "Suburb",
        "Small town",
        "Village",
        "Countryside",
        "Forest",
        "Mountains",
        "Beach",
        "Island",
        "Desert",
        "Jungle",
        "Arctic",
        "Tundra",
        "Plains",
        "Savanna",
        "Canyon",
        "Valley",
        "Cave",
        "Ruins",
        "Underwater",
        "Space station",
        "Alien planet",
        "Parallel universe",
        "Historical period (e.g., medieval castle, ancient civilization)",
        "Futuristic cityscape",
        "Dystopian society",
        "Post-apocalyptic wasteland",
        "Magical realm",
        "Fairy tale kingdom",
        "Dream world"
    ],
    season: ["spring", "summer", "autumn", "winter"],
    atmospheres: [
        "Calm",
        "Eerie",
        "Bustling",
        "Tranquil",
        "Tense",
        "Magical",
        "Foreboding",
        "Chaotic",
        "Serene",
        "Melancholic",
        "Romantic",
        "Enigmatic",
        "Exciting",
        "Dreamy",
        "Grim",
        "Hopeful",
        "Surreal",
        "Lively",
        "Intense",
        "Peaceful"
    ]
}